### PR TITLE
Fix accordion widget

### PR DESCRIPTION
**Pull request by pbugnion**
This PR fixes an error where the accordion widget wasn't working. In particular:

- we now include the built version of the ipywidgets stylesheet, rather than the source. The built version has gone through cssnext, which introduces browser compatibility.
- we include the PhosphorJS style sheet.

### CODE REVIEW

**Comment by DougRzz** [comment]
Hi @pbugnion .  Thanks for doing this. A working accordion widget in ipywidgets-server would be a big bonus.  However....   I installed this alpha version using 'pip install --pre ipywidgets-server'.  Unfortunately, I am just getting a blank page in the browser.   No error messages.  Only warning in the cmd window is 'WARNING:tornado.access:404 GET /favicon.ico ' .  Is there anything I can do to help debug this?

**Comment by pbugnion** [comment]
Hi -- sorry, that alpha release wasn't really ready for testing. Updating the dependencies broke a few things because of changes in some of the underlying JupyterLab packages (which are still in alpha).

I've just released `0.2.2-alpha2` which fixes the accordion widget -- if you have time, some feedback on whether that works for you would be great (`pip install ipywidgets-server==0.2.2-alpha2`). 

Embedding widgets in output widgets does not work on this release (yet), but I think this is a relatively straightforward fix. Embedding matplotlib plots in output widgets is also pretty broken, but that seems to be due to an incompatibility between a recent release of matplotlib and ipywidgets. I suspect the answer to this will involve moving the examples to use ipympl (?).

**Comment by DougRzz** [comment]
With alpha2, the served dashboard is now back. Thanks.    However, the accordion widget still doesn't work.   It is just the same as v0.2.1.   

Here are the differences in the accordion widget when inspecting in Google Chrome.

**From ipywidgets-server:**
image

**From Jupyter Notebook v5.4:**
image

**Comment by pbugnion** [comment]
Thanks very much for looking into this.

That's strange, because we don't even serve the old stylesheet any more. Are you sure you've refreshed your cache so you aren't serving an old stylesheet? In Chrome, to refresh, you can open the browser console (this automatically disables caching) and force a complete refresh with `Ctrl-Shift-R`.

The extra webkit entries are not actually directly relevant, as far as I can tell. We were missing a stylesheet from phosphorjs that defines the behaviour of widgets when hidden. If you inspect one of the hidden sections of the accordion, they should have the class `p-mod-hidden` and that class should be defined as `display: none !important;`:

screen shot 2018-03-21 at 07 10 00

**Comment by DougRzz** [comment]
I rebooted the computer and refreshed the google chrome console.  It still doesn't work.

There is no "p-mod-hidden". This is what I get when inspecting one of the panels which should be hidden:
image

**Comment by DougRzz** [comment]
If I add to one of the accordions

```
.p-Widget.p-Panel.p-Collapse-contents.p-mod-hidden {
    display: none;
```

All the accordions now work.

**Comment by DougRzz** [comment]
It works if I add the above to the index.html !!  Probably a bit of a hack but at the very least it's a temporary fix.  Let me know you want me to do any testing if you want to find another solution.   Thanks for the help.

**Comment by pbugnion** [comment]
I've tried the current version on a fresh VM, and it works fine. If @DougRzz (or anyone else) wants to try it out:

```
pip install ipywidgets-server==0.2.2-alpha3
```

The matplotlib examples remain somewhat broken, but that predates this PR.

**Comment by DougRzz** [comment]
@pbugnion I've tested this and it works nicely.  Thanks!

**Comment by pbugnion** [comment]
Awesome, thank you!

**Pull request merged**
